spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: http://localhost:8080
          predicates:
            - Path=/customer/**

        - id: ACCOUNT-SERVICE
          uri: http://localhost:8181
          predicates:
            - Path=/account/**
server:
  port: 8282

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30

info:
  app:
    name: apiGateway
    description:  api Gateway Services
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  info:
    env:
      enabled: true
    info:
      enabled: true
